# This workflow builds and uploads the Docker images to DockerHub.
#
# We do not want the Docker image tag to start with 'v'.
# So we are using the release name; which should not have a preceding 'v'.
# The release tag has a preceding 'v'.
name: build-push

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push - Ubuntu
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: prohde/virtuoso-opensource-7:latest,prohde/virtuoso-opensource-7:7,prohde/virtuoso-opensource-7:7.2,prohde/virtuoso-opensource-7:${{ github.event.release.name }}
      - name: Build and Push - Alpine
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.alpine
          push: true
          tags: prohde/virtuoso-opensource-7:7-alpine,prohde/virtuoso-opensource-7:7.2-alpine,prohde/virtuoso-opensource-7:${{ github.event.release.name }}-alpine

